<?php

namespace Database\Seeders;

use App\Models\Faq\Faq;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

/**
 * Hizmet x bölge sayfalarını farklılaştırmak için bölgeye özel SSS havuzu —
 * her hizmet için 10 soru. Metinlerde {{region}} yer tutucusu kullanılır
 * (bkz. App\Support\Placeholder): bölgeli sayfada "Gaziantep Şahinbey" olarak
 * çözülür, bölgesiz şemsiye sayfada tamamen kalkar ve cümle yine düzgün okunur.
 *
 * Seeder soruları YALNIZCA havuza yazar; hangi sorunun hangi hizmete
 * bağlanacağı panelden seçilir (Hizmet formu > Sıkça Sorulan Sorular).
 * Dizideki gruplama yalnızca hangi sorunun hangi hizmet için yazıldığını
 * gösterir, bir bağ kurmaz.
 *
 * Tekrar çalıştırılabilir: aynı soru metni ikinci kez eklenmez, panelden
 * düzenlenmiş cevap ezilmez.
 */
class ServiceFaqSeeder extends Seeder
{
    // Model olayları kapalı: 60 kayıt denetim kaydını ve revizyon geçmişini
    // şişirmesin. Bu yüzden sort_order elle veriliyor — HasSortOrder onu
    // "creating" olayında atar, olaylar kapalıyken çalışmaz.
    use WithoutModelEvents;

    /** Hizmet adı => (soru => cevap). Sıra, panelde listelenme sırasıdır. */
    private const FAQS = [
        'Web Tasarım' => [
            '{{region}} web sitesi fiyatları ne kadar?' => '{{region}} için hazırladığımız web sitelerinde sabit bir liste fiyatı yoktur; ücret sayfa sayısı, özel tasarım isteği, içerik ve fotoğraf üretimi, çoklu dil ya da e-ticaret gibi ihtiyaçlara göre belirlenir. İhtiyacınızı kısa bir görüşmede netleştirip kapsamı ve süreyi kalem kalem gösteren yazılı bir teklif iletiyoruz. Teklif onaylandıktan sonra kapsam dışına çıkılmadığı sürece sürpriz ek ücret çıkmaz.',
            'Bir web sitesi ne kadar sürede yapılır?' => 'Kurumsal web siteleri, içerik ve görseller zamanında iletildiğinde çoğunlukla 1-3 hafta içinde yayına alınır. E-ticaret ya da özel modül gerektiren projelerde süre kapsamla birlikte uzar; proje başında takvimi aşamalara bölüp yazılı olarak paylaşıyoruz. {{region}} içindeki işletmelerle süreci çevrim içi yürüttüğümüz için onay turları teslimi geciktirmiyor.',
            '{{region}} içindeki bir firmayla çalışmak için yüz yüze görüşme şart mı?' => 'Hayır. Görüşmeleri telefon, WhatsApp ve çevrim içi toplantıyla yürütüyoruz; tasarım onayları, revizyonlar ve teslim eğitimi de aynı şekilde ilerliyor. {{region}} içindeki işletmeler için talep ederseniz yerinde görüşme planlanabilir, ancak projenin ilerlemesi için zorunlu değildir.',
            '{{region}} için yapılan web siteleri mobil uyumlu ve hızlı mı?' => 'Evet. Sayfalar mobil öncelikli kesiliyor, görseller uygun boyut ve güncel formatlarda sunuluyor; teslim öncesinde Google’ın Core Web Vitals ölçümlerini kontrol ediyoruz. {{region}} aramalarının büyük bölümü cep telefonundan geldiği için mobil hız hem sıralamayı hem de gelen aramaya dönüşme oranını doğrudan etkiler.',
            '{{region}} web sitesi için benden hangi bilgiler isteniyor?' => 'Logonuz (varsa kaynak dosyası), kurumsal renkleriniz, hizmet veya ürün listeniz, iletişim bilgileriniz, referanslarınız ve kendi çektiğiniz fotoğraflar başlamak için yeterlidir. Metin yazmakla uğraşmak istemezseniz hizmet açıklamalarını ve {{region}} odaklı sayfa içeriklerini biz hazırlıyoruz, siz yalnızca okuyup onaylıyorsunuz.',
            'Hazır tema mı özel tasarım mı — {{region}} işletmem için hangisi doğru?' => 'Hazır tema hızlı ve düşük maliyetlidir; karşılığında {{region}} içinde aynı temayı kullanan başka siteler olabilir ve kullanılmayan kod yükü hız puanını aşağı çeker. Özel tasarım markanızın kimliğine ve dönüşüm hedefinize göre kurgulanır, uzun vadede SEO ve reklam performansındaki fark buradan çıkar. Bütçenize ve aciliyetinize göre hangisinin daha mantıklı olduğunu görüşmede açıkça söylüyoruz.',
            '{{region}} web sitesi SEO’ya uygun olarak mı teslim ediliyor?' => 'Evet. Başlık ve açıklama etiketleri, başlık hiyerarşisi, görsel alt metinleri, okunabilir adres yapısı, site haritası, robots.txt ve Schema.org işaretlemesi teslimin parçasıdır. {{region}} gibi bölge odaklı sayfalar için yerel SEO alanları da hazır gelir; sürekli içerik üretimi ve bağlantı çalışması ise ayrıca yürüyen SEO danışmanlığı kapsamındadır.',
            '{{region}} web sitemi kendim güncelleyebilir miyim?' => 'Evet. Teslim ettiğimiz yönetim paneliyle sayfaları, blog yazılarını, görselleri, hizmetleri ve iletişim bilgilerinizi kod bilmeden güncelleyebilirsiniz. Teslimde ekranları birlikte gezdiğimiz bir eğitim yapıyoruz; sonrasında takıldığınız noktada destek veriyoruz.',
            '{{region}} web sitesi fiyatına alan adı ve hosting dahil mi?' => 'Alan adı ve hosting teklifte ayrı kalemler olarak görünür; ilk yıl paketin içinde verilebilir, sonraki yıllar yıllık yenileme ücretine tabidir. Alan adının sahibi her zaman sizsiniz — kayıt sizin adınıza yapılır ve dilediğiniz zaman başka bir sağlayıcıya taşıyabilirsiniz.',
            'Mevcut {{region}} web sitemi yenilersem Google sıralamalarımı kaybeder miyim?' => 'Doğru yürütülen bir yenilemede kaybetmezsiniz. Yenileme öncesinde mevcut adresleri ve trafik alan sayfaları listeliyor, adresi değişen her sayfa için eskisinden yenisine 301 yönlendirmesi kuruyoruz; böylece Google birikmiş değeri yeni sayfaya taşır. {{region}} aramalarındaki sıralamalarınızı yayın sonrası ilk haftalarda takip edip sapma olursa hemen müdahale ediyoruz.',
        ],

        'SEO Danışmanlığı' => [
            '{{region}} SEO çalışması ne kadar sürede sonuç verir?' => 'İlk teknik iyileştirmelerin etkisi birkaç hafta içinde görülebilir; rekabetçi anahtar kelimelerde kalıcı sıralama ise genellikle 3-6 aylık istikrarlı çalışma ister. Süre sitenizin yaşı, teknik durumu, içerik birikimi ve {{region}} içindeki rekabetin yoğunluğuna göre değişir. Her ay hangi işin yapıldığını ve hangi kelimede nereye gelindiğini raporda görürsünüz.',
            '{{region}} SEO danışmanlığı fiyatları nasıl belirleniyor?' => 'SEO tek seferlik bir iş değil, aylık yürüyen bir çalışmadır; bu yüzden ücret aylık olarak ve kapsama göre belirlenir. Kapsamı hedeflenen anahtar kelime sayısı, aylık içerik üretimi, teknik düzeltme yükü ve raporlama sıklığı oluşturur. Önce sitenizi ücretsiz inceleyip {{region}} için nereden başlanması gerektiğini konuşuyor, bütçeyi ondan sonra netleştiriyoruz.',
            '{{region}} yerel SEO nedir, neden önemlidir?' => 'Yerel SEO, kullanıcı hizmetinizi bulunduğu yerle birlikte aradığında (“{{region}} web tasarım” gibi) sizi arama sonuçlarında ve Google Haritalar listesinde üst sıralara taşıyan çalışmadır. Google İşletme Profili, bölgeye özel hizmet sayfaları, her yerde tutarlı adres-telefon bilgisi ve müşteri yorumları bu işin bel kemiğidir. Hizmet verdiğiniz bölgeyi arayan kullanıcı satın almaya en yakın kullanıcıdır; yerel SEO’nun dönüşüm oranı bu yüzden genel aramalardan yüksektir.',
            '{{region}} aramalarında ilk sayfaya çıkma garantisi veriyor musunuz?' => 'Hayır — sıralama Google’ın algoritmasına ve rakiplerin hareketine bağlı olduğu için kimse gerçekçi bir garanti veremez, garanti vaadi Google’ın kendi yönergelerine de aykırıdır. Bizim taahhüdümüz yapılacak işin kapsamı ve ölçümün şeffaflığıdır: {{region}} için hedeflenen kelimelerin başlangıç sıralamasını kaydeder, her ay aynı yöntemle ölçüp değişimi olduğu gibi gösteririz.',
            '{{region}} SEO çalışmasında tam olarak hangi işler yapılıyor?' => 'Çalışma dört başlıkta yürür: teknik SEO (hız, indeksleme, kırık bağlantılar, işaretlemeler), içerik (bölge ve hizmet odaklı sayfalar, blog), yerel SEO (Google İşletme Profili, harita sıralaması, yorum yönetimi) ve otorite (kaliteli bağlantılar, marka bahisleri). {{region}} için hangi başlığın en hızlı kazanç getirdiğini ölçerek başlıyor, her ay yapılan işi kalem kalem raporluyoruz.',
            '{{region}} Google Haritalar sonuçlarında üst sıralara çıkmak mümkün mü?' => 'Mümkün; harita sıralaması büyük ölçüde işletmenin aranan yere yakınlığı, profilin eksiksizliği, kategori seçimi ve yorumların sayısı ile güncelliğine bağlıdır. Profili doğru kategorilerle kurar, hizmet ve fotoğraf alanlarını doldurur, yorum akışını düzenli hale getiririz. {{region}} içinde adresinizin bulunduğu noktadan uzak aramalarda sıralamanın düşmesi normaldir; bu yüzden hedef bölgeyi gerçekçi seçmek gerekir.',
            '{{region}} SEO çalışmasının sonuçlarını nasıl takip edeceğim?' => 'Google Analytics 4 ve Search Console hesaplarınız üzerinden; trafiğin nereden geldiğini, hangi sorguların tıklandığını ve formla telefonla gelen taleplerin sayısını görürsünüz. Buna ek olarak {{region}} için hedeflenen anahtar kelimelerin sıralama değişimini ve o ay yapılan işleri içeren aylık bir rapor gönderiyoruz. Hesaplar sizin adınıza açılır, verilere her zaman doğrudan erişiminiz olur.',
            '{{region}} içindeki rakiplerim neden benden üstte çıkıyor?' => 'En sık nedenler şunlardır: rakibin sitesi daha eski ve daha fazla bağlantı biriktirmiş, arama niyetine daha iyi cevap veren içerikleri var, Google İşletme Profili daha eksiksiz ve yorumları daha güncel ya da sizin siteniz teknik olarak yavaş ve mobilde zorlanıyor. {{region}} için ilk adımda rakip analizi yapıp aradaki farkı başlık başlık listeliyoruz; böylece bütçenin hangi açığı kapatacağı baştan belli olur.',
            'Web sitem yeni — {{region}} SEO çalışmasına şimdiden başlamalı mıyım?' => 'Evet, en doğru zaman sitenin ilk günleridir: adres yapısı, başlık kurgusu ve içerik planı baştan doğru kurulduğunda sonradan düzeltme maliyeti ortadan kalkar. Yeni sitelerde Google’ın güven kazanması zaman aldığı için {{region}} gibi bölge odaklı ve rekabeti daha düşük aramalardan başlayıp yukarı doğru ilerlemek daha hızlı sonuç verir.',
            'SEO çalışmasını bıraktığımda {{region}} sıralamalarım düşer mi?' => 'Kazanılan sıralama bir gecede kaybolmaz; teknik iyileştirmeler ve yayımlanan içerikler yerinde kalır. Ancak rakipler çalışmaya devam ettiği ve Google algoritmasını güncellediği için ara verildiğinde sıralamalar zamanla geriler. {{region}} içinde rekabetin yoğun olduğu kelimelerde en azından içerik tazeleme ve teknik bakımın sürdürülmesini öneriyoruz.',
        ],

        'Özel Yazılım Geliştirme' => [
            '{{region}} özel yazılım geliştirme maliyeti nasıl hesaplanıyor?' => 'Maliyet ekran ve modül sayısı, iş akışının karmaşıklığı, entegrasyon ihtiyacı (muhasebe, kargo, banka, e-fatura) ve kullanıcı yetki yapısına göre çıkar. Önce kısa bir analiz görüşmesi yapıp kapsamı yazıya döküyor, ardından modül modül fiyatlandırılmış bir teklif iletiyoruz. {{region}} içindeki işletmelere, bütçeyi tek seferde bağlamamak için projeyi aşamalara bölerek ilerleme seçeneği de sunuyoruz.',
            '{{region}} işletmem için hazır program mı özel yazılım mı daha doğru?' => 'İş akışınız sektörün standart akışına uyuyorsa hazır program hem hızlı hem ekonomiktir. Ancak kendi usulünüze göre çalışıyorsanız, hazır programda her ay aynı işi elle telafi etmeye başlarsınız — özel yazılım tam bu noktada kendini amorti eder. {{region}} içindeki iş akışınızı dinleyip hangisinin doğru olduğunu, özel yazılım gerekmiyorsa gerekmediğini de açıkça söylüyoruz.',
            '{{region}} özel yazılım projesi ne kadar sürede teslim edilir?' => 'Tek bir iş akışını çözen küçük kapsamlı projeler genellikle 4-8 hafta, çok modüllü sistemler ise kapsama göre daha uzun sürer. Süreyi tek bir tarihe bağlamak yerine aşamalara bölüyoruz: her aşamanın sonunda çalışan bir sürümü görür, geri bildiriminiz sonraki aşamaya girer. Böylece {{region}} içindeki ekibiniz sistemi baştan kullanmaya başlar, alışma süreci teslimi beklemez.',
            '{{region}} özel yazılım projelerinde hangi teknolojileri kullanıyorsunuz?' => 'Sunucu tarafında PHP ve Laravel, veritabanında MySQL, arayüzde ise güncel web standartlarını kullanıyoruz. Yazılım tarayıcı üzerinden çalıştığı için bilgisayar, tablet ve telefondan kurulum gerektirmeden erişilir; {{region}} dışındaki şubeleriniz de aynı sisteme bağlanır. Yaygın ve belgelenmiş teknolojileri tercih ediyoruz ki yarın başka bir ekip devraldığında kod yabancı kalmasın.',
            '{{region}} işletmemdeki mevcut muhasebe veya ERP programıyla entegre olabilir mi?' => 'Programın bir API’si, web servisi ya da veri aktarım dosyası varsa entegrasyon kurulabilir; e-fatura, kargo, sanal POS ve pazaryeri entegrasyonları da aynı şekilde yapılır. Analiz aşamasında mevcut programın belgelerini inceleyip neyin gerçekten mümkün olduğunu, neyin elle aktarım olarak kalacağını yazılı söylüyoruz — tahminle söz vermiyoruz.',
            '{{region}} için geliştirilen yazılımın kaynak kodu bize mi ait olur?' => 'Evet. Teslimde kaynak kodun tamamı ve veritabanı şeması sizin olur; kodu kendi sunucunuza kurabilir, dilerseniz başka bir ekiple geliştirmeye devam edebilirsiniz. Lisans ya da abonelik adı altında kodu rehin tutan bir model uygulamıyoruz; sözleşmede bu madde açıkça yazılıdır.',
            'Teslimden sonra {{region}} içinde destek ve bakım veriyor musunuz?' => 'Evet. Teslim sonrası belirli bir süre boyunca hata düzeltmeleri garanti kapsamındadır; sonrasında aylık bakım ve geliştirme anlaşmasıyla devam edebilirsiniz. Bakım kapsamında güvenlik güncellemeleri, yedek kontrolü ve küçük geliştirme talepleri yer alır. {{region}} içindeki kullanıcılarınız için kısa bir kullanım eğitimi ve ekran kayıtları da teslimin parçasıdır.',
            '{{region}} için geliştirilen yazılım kendi sunucumuzda mı bulutta mı çalışır?' => 'İkisi de mümkün. Verilerin şirket içinde kalması gerekiyorsa kendi sunucunuza kuruyoruz; sunucu bakımıyla uğraşmak istemiyorsanız bulutta yönetilen bir ortama kuruyor, yedek ve güncellemeleri biz takip ediyoruz. {{region}} içindeki internet altyapınıza ve kullanıcı sayınıza göre hangisinin daha güvenli ve ekonomik olduğunu birlikte kararlaştırıyoruz.',
            '{{region}} özel yazılım projesine nasıl başlıyoruz?' => 'Süreç analizle başlar: mevcut iş akışınızı, kullandığınız formları ve kimin hangi ekranı kullanacağını konuşup ihtiyaç listesini çıkarıyoruz. Ardından kapsam ve takvim yazıya dökülür, onay sonrası ekran taslaklarıyla geliştirmeye geçilir. {{region}} içindeki ekibinizden bir kişinin süreçte irtibat kişisi olması işi belirgin biçimde hızlandırır.',
            '{{region}} özel yazılım projelerinde veri güvenliği ve KVKK uyumu nasıl sağlanıyor?' => 'Erişim rol ve yetki bazlı kurulur, kritik alanlar şifreli saklanır, işlem geçmişi kayıt altına alınır ve düzenli yedekleme kurgulanır. Kişisel veri toplayan ekranlarda KVKK gereği aydınlatma metni, açık rıza ve saklama süresi mantığı yazılımın içine yerleştirilir. Böylece {{region}} içindeki müşteri verileriniz hem teknik hem hukuki tarafta savunulabilir bir düzende tutulur.',
        ],

        'e-Ticaret Yönetim Hizmeti' => [
            '{{region}} e-ticaret yönetim hizmeti neleri kapsıyor?' => 'Ürün ve kategori düzeni, fiyat-stok güncellemeleri, kampanya ve kupon kurgusu, ödeme ile kargo entegrasyonlarının takibi, ürün sayfalarının SEO düzenlemesi, reklam yönetimi ve raporlama hizmetin kapsamındadır. {{region}} içindeki işletmenizin hangi kalemlerde desteğe ihtiyacı olduğunu birlikte belirleyip paketi ona göre kuruyoruz — kullanmadığınız kalem için ödeme yapmıyorsunuz.',
            '{{region}} e-ticaret sitesi kurmak ne kadar tutar?' => 'Maliyet ürün sayısı, varyant yapısı (renk, beden, paket), istenen ödeme ve kargo entegrasyonları, pazaryeri bağlantıları ve tasarımın özel olup olmamasına göre değişir. Hazır altyapı üzerine kurulan mağazalar daha ekonomik başlar; kendi altyapısı yazılan projeler daha yüksek bütçe ister ama sınırsız esneklik verir. {{region}} için hangi yolun mantıklı olduğunu ürün ve sipariş hacminize bakarak söylüyoruz.',
            '{{region}} e-ticaret sitemin yanında Trendyol ve Hepsiburada gibi pazaryerlerini de yönetiyor musunuz?' => 'Evet. Pazaryeri mağazalarının açılışı, ürün aktarımı, fiyat-stok eşitlemesi ve kampanya takibi ayrı bir kalem olarak yürütülebilir. {{region}} içindeki satıcılara önerimiz her zaman aynı: pazaryeri hacim getirir ama komisyon ve rekabet baskısı yüksektir, kendi siteniz kârın kalıcı olduğu yerdir — ikisini birlikte, stok tek yerden eşitlenerek yürütmek en sağlıklısıdır.',
            '{{region}} e-ticaret sitem için hangi altyapıyı önerirsiniz?' => 'Ürün sayınız sınırlı ve standart bir satış akışınız varsa hazır e-ticaret altyapıları hızlı ve ekonomik başlangıç sağlar. Kendinize özgü fiyatlandırma, bayi/toptan yapısı ya da ERP entegrasyonu gerekiyorsa özel geliştirme daha doğru olur. {{region}} içindeki sipariş hacminizi, ürün yapınızı ve büyüme planınızı dinleyip hangisinin toplam maliyeti düşürdüğünü açıkça söylüyoruz.',
            '{{region}} e-ticaret sitem için ürün fotoğrafı ve açıklamalarını siz mi hazırlıyorsunuz?' => 'Ürün açıklamalarını, kategori metinlerini ve SEO başlıklarını arama hacmine göre biz yazabiliriz; üretici metinlerini birebir kopyalamıyoruz çünkü aynı metin yüzlerce sitede geçtiğinde Google için kopya içerik olur. Fotoğraf tarafında elinizdeki görselleri düzenleyip standart ölçüye getiriyoruz, sıfırdan ürün çekimi gerekiyorsa {{region}} içinde bu iş ayrı bir kalem olarak planlanır.',
            '{{region}} e-ticaret sitesinde ödeme ve kargo entegrasyonları nasıl kuruluyor?' => 'Sanal POS ve taksit tanımları anlaşmalı olduğunuz bankanın sağladığı bilgilerle kurulur; kargo tarafında anlaşmalı firmanın sistemine bağlanarak gönderi ve takip numarası akışı otomatikleştirilir. Başvuru ve sözleşme süreçleri banka ile kargo firmasının kendi onay süresine bağlıdır. {{region}} içindeki teslimat alışkanlıklarına göre kapıda ödeme, aynı gün teslim gibi seçenekleri de kurguya ekleyebiliyoruz.',
            '{{region}} e-ticaret sitem ziyaret alıyor ama satış yok, sebebi ne olabilir?' => 'En sık nedenler: mobilde yavaş açılan sayfalar, güven vermeyen tasarım ve eksik iletişim bilgisi, zorunlu üyelik isteyen uzun sepet akışı, belirsiz kargo ücreti ile teslim süresi, zayıf ürün fotoğrafı ve kopya ürün açıklamaları. {{region}} için önce ölçüm kuruyoruz — hangi adımda kaç kişinin düştüğünü gördükten sonra en çok kaybın olduğu adımdan başlayıp iyileştiriyoruz; tahminle tasarım değiştirmiyoruz.',
            '{{region}} e-ticaret sitem için aylık ne kadar reklam bütçesi ayırmalıyım?' => 'Bütçe kâr marjınıza, sepet ortalamanıza ve rekabete bağlıdır; doğru yaklaşım ürün başına kazancı hesaplayıp kabul edilebilir bir müşteri edinme maliyeti belirlemek ve test için makul bir tutarla başlamaktır. İlk haftaların verisi hangi kampanyanın kâr getirdiğini gösterir, bütçe oradan büyütülür. {{region}} çevresinde teslimat avantajınız varsa reklamları o bölgeye odaklamak maliyeti belirgin biçimde düşürür.',
            '{{region}} e-ticaret yönetimi hizmeti kaç aylık sözleşmeyle veriliyor?' => 'Yönetim hizmeti aylık yürür; sonuç almak veri toplamaya bağlı olduğu için en az üç aylık bir başlangıç dönemi öneriyoruz, çünkü ilk ay çoğunlukla ölçüm kurma ve düzeltme ayıdır. Uzun vadeli taahhüt zorunlu değildir, hizmeti dilediğiniz ayın sonunda bırakabilirsiniz; hesap, panel ve reklam varlıklarının tamamı sizin adınıza kayıtlı kalır.',
            'Mevcut {{region}} e-ticaret sitemi verileriyle birlikte taşıyabilir misiniz?' => 'Evet. Ürünler, kategoriler, müşteri kayıtları ve sipariş geçmişi yeni altyapıya aktarılabilir; aktarım öncesinde test kopyası üzerinde deneyip eksik alan kalmadığını doğruluyoruz. Adresi değişen ürün ve kategori sayfaları için 301 yönlendirmeleri kuruyoruz, böylece {{region}} aramalarındaki mevcut sıralamalarınız ve siteye gelen bağlantılar boşa gitmez.',
        ],

        'Google İşletme Kaydı' => [
            '{{region}} Google işletme kaydı nasıl açılır?' => 'Kayıt, Google İşletme Profili üzerinden işletme adı, kategori, adres, çalışma saatleri ve iletişim bilgileriyle oluşturulur; ardından Google adresi kartpostal, telefon, e-posta ya da video ile doğrular. Doğrulama tamamlanınca işletmeniz {{region}} aramalarında ve Google Haritalar sonuçlarında görünmeye başlar. Süreci baştan sona biz yürütüyoruz: kategori seçimi, hizmet listesi, fotoğraflar ve açıklama metni dahil.',
            '{{region}} Google işletme kaydı ücretli mi?' => 'Google İşletme Profili’ni açmak ve kullanmak Google tarafında ücretsizdir; “kaydınız silinecek, ücret yatırın” diyen aramalar dolandırıcılıktır. Ücretlendirdiğimiz şey Google’ın kendisi değil; profilin doğru kurulması, {{region}} içinde harita sıralamasına göre optimize edilmesi ve fotoğraf-hizmet-yorum akışının düzenli yönetilmesidir.',
            'Fiziksel dükkânım yok — {{region}} için Google işletme kaydı açabilir miyim?' => 'Evet. Müşteriye gidilerek çalışan işletmeler adres göstermeden “hizmet bölgesi” tanımlayarak kayıt açabilir; bu durumda adres gizli kalır, yalnızca hizmet verdiğiniz bölgeler listelenir. Ev adresinizi herkese açık yayımlamanız gerekmez. Bu kurulumda {{region}} ve çevresini hizmet bölgesi olarak tanımlıyor, kategori ve hizmet alanlarını buna göre dolduruyoruz.',
            '{{region}} Google işletme kaydım neden doğrulanmıyor?' => 'En sık nedenler: tabelayla birebir aynı olmayan işletme adı, kargo kutusu ya da paylaşımlı ofis gibi kabul görmeyen adres, aynı adreste kayıtlı başka bir işletme, adres bilgilerinin resmi kayıtlarla uyuşmaması ve reddedilen doğrulama sonrası aynı bilgilerle tekrar denenmesi. {{region}} içindeki kaydınızı inceleyip hangi kalemin takıldığını tespit ediyor, gerekli belgelerle itiraz sürecini yürütüyoruz.',
            'Google İşletme Profilim askıya alındı, {{region}} içinde yeniden açılabilir mi?' => 'Çoğu durumda mümkün. Askıya alma genellikle ad-kategori-adres uyumsuzluğu, kısa sürede yapılan çok sayıda değişiklik, yönerge dışı anahtar kelime doldurma ya da sahte yorum şüphesinden kaynaklanır. Profili yönergeye uygun hale getirip vergi levhası, tabela fotoğrafı ve fatura gibi belgelerle itiraz ediyoruz. Kararı Google verdiği için sonuç garanti edilemez; {{region}} kaydınızın geçmişine göre sürecin ne kadar sürebileceğini baştan söylüyoruz.',
            '{{region}} Google Haritalar sıralamasında nasıl üst sıralara çıkarım?' => 'Harita sıralamasında üç şey belirleyicidir: aranan konuma yakınlık, profilin eksiksizliği ve işletmenin bilinirliği. Doğru ana kategori, eksiksiz hizmet listesi, düzenli fotoğraf ve gönderi paylaşımı, sürekli gelen yorumlar ile yorumlara verilen yanıtlar, web sitesinde {{region}} odaklı bir hizmet sayfası ve her yerde tutarlı adres-telefon bilgisi birlikte çalışır. Yakınlık değiştirilemeyeceği için hedef bölgeyi gerçekçi belirlemek şarttır.',
            '{{region}} işletme profilime gelen olumsuz yorumlar silinebilir mi?' => 'Yalnızca Google’ın yönergesini ihlal eden yorumlar (küfür, alakasız içerik, rakip saldırısı, hiç müşteri olmamış kişinin yorumu) şikâyet yoluyla kaldırılabilir; sadece olumsuz olduğu için bir yorum silinmez. Bu tür yorumları raporlayıp süreci takip ediyoruz. Kalan olumsuz yorumlarda doğru strateji, {{region}} içindeki memnun müşterilerden düzenli yorum akışı kurmak ve her yoruma ölçülü bir yanıt yazmaktır.',
            '{{region}} Google işletme profilimi ne sıklıkla güncellemem gerekiyor?' => 'Profil hareketli kaldığında harita sıralaması da olumlu etkilenir; ayda birkaç fotoğraf, dönemsel bir gönderi veya kampanya, yeni hizmet eklemesi ve tatil günlerinde çalışma saati güncellemesi iyi bir ritimdir. Yorumlara mümkün olduğunca kısa sürede yanıt verilmesi de önemlidir. {{region}} için bu akışı takvime bağlayıp düzenli yürütüyoruz.',
            '{{region}} dışında şubelerim var, her biri için ayrı kayıt mı gerekir?' => 'Evet. Her fiziksel şube kendi adresi, telefonu ve çalışma saatleriyle ayrı bir kayıt olarak açılır; aynı kayıtta birden fazla adres tanımlanamaz. Şubeler tek hesap altında toplanır, böylece yönetim tek panelden yürür. Web sitesinde de her şube için ayrı bir bölge sayfası kurgulamak {{region}} ve diğer şube bölgelerindeki aramalarda belirgin avantaj sağlar.',
            'Google işletme kaydı {{region}} için web sitesinin yerine geçer mi?' => 'Geçmez, ikisi birbirini besler. İşletme kaydı sizi haritada bulunur kılar; web sitesi ise hizmetlerinizi anlatır, referans ve fiyat bilgisiyle güven verir ve profilinizde bağlantı olarak yer alarak sıralamanızı destekler. Sitesi olmayan profiller {{region}} içindeki rekabetçi aramalarda genellikle geri planda kalır.',
        ],

        'Google Ads Reklam Yönetimi' => [
            '{{region}} Google Ads reklamları için aylık ne kadar bütçe gerekir?' => 'Bütçe, hedeflediğiniz kelimelerin tıklama maliyetine ve {{region}} içindeki arama hacmine göre belirlenir; doğru yöntem bir müşteri kazanmanın kaç tıklamaya mal olduğunu hesaplayıp buna göre başlangıç bütçesi çıkarmaktır. Az sayıda ama satın almaya en yakın kelimeyle test edip veriye göre büyütmek, bütçeyi geniş hedeflemeye yaymaktan her zaman daha verimlidir. Görüşmede sektörünüz için gerçekçi bir başlangıç aralığı belirliyoruz.',
            '{{region}} Google Ads yönetim ücreti nasıl belirleniyor?' => 'Yönetim ücreti reklam bütçesinden ayrıdır: bütçe doğrudan Google’a gider, yönetim ücreti kampanya kurulumu, düzenli optimizasyon, dönüşüm takibi ve raporlama karşılığıdır. Kampanya sayısı ve bütçe büyüklüğüne göre aylık sabit ücret ya da bütçeye oranlı bir model uygulanır. {{region}} için hangisinin size daha uygun olduğunu baştan yazılı olarak belirliyoruz.',
            '{{region}} Google Ads reklamları ne zaman sonuç vermeye başlar?' => 'SEO’dan farklı olarak reklamlar yayına alındığı gün görünmeye başlar; ilk aramalar genellikle ilk günlerde gelir. Ancak hangi kelimenin gerçekten müşteri getirdiğinin netleşmesi ve maliyetin optimize edilmesi için 2-4 haftalık veri gerekir. {{region}} içindeki arama hacmi düşükse veri birikmesi daha uzun sürebilir; bu durumda hedef bölgeyi ve kelime setini birlikte genişletiyoruz.',
            'Reklamlarımı yalnızca {{region}} ile sınırlandırabilir miyiz?' => 'Evet. Hedefleme il, ilçe, posta kodu ya da bir noktanın çevresindeki yarıçap olarak tanımlanabilir; böylece bütçe hizmet vermediğiniz yerlere harcanmaz. Ayrıca “bölgede bulunan kullanıcı” ile “bölgeyi arayan kullanıcı” ayrımı da ayarlanır — bu detay atlandığında {{region}} için ayrılan bütçe başka şehirlerdeki tıklamalara gider. Reklam metinlerinde bölge adının geçmesi de tıklama oranını yükseltir.',
            '{{region}} işletmem için hangi Google Ads kampanya türü uygun?' => 'Hizmet satıyorsanız ve insanlar ihtiyacı aratıyorsa Arama Ağı kampanyası temeldir; e-ticarette ürün görselleriyle çıkan Alışveriş kampanyaları öne geçer. Bilinirlik ve yeniden pazarlama için Görüntülü Reklam Ağı ile YouTube, yerelde ise Google Haritalar üzerinden gelen aramalar işe yarar. {{region}} içindeki hedefinize göre hangi türle başlanacağını, hangisinin boş bütçe yakacağını baştan söylüyoruz.',
            '{{region}} için Google Ads mi SEO mu daha doğru?' => 'İkisi farklı işler yapar: Google Ads bütçe ayırdığınız gün trafik getirir ama durdurduğunuzda biter, SEO yavaş büyür ama kalıcıdır. Yeni bir siteyle {{region}} içinde hızlı talep gerekiyorsa reklamla başlamak, aynı anda SEO çalışmasını yürütüp reklam bağımlılığını zamanla azaltmak en sağlıklı yoldur. Reklam verisi hangi kelimenin gerçekten müşteri getirdiğini gösterdiği için SEO içerik planını da isabetli hale getirir.',
            '{{region}} reklamlarım tıklanıyor ama müşteriye dönüşmüyor, neden?' => 'Sık görülen nedenler: reklamın indiği sayfa ile aranan şeyin uyuşmaması, sayfada telefon ve form gibi net bir eyleme çağrının bulunmaması, mobilde yavaş açılan sayfa, fiyat ve kapsam belirsizliği, satın alma niyeti taşımayan geniş kelimelerin hedeflenmesi ve gelen aramaların zamanında yanıtlanmaması. {{region}} için dönüşüm takibini kurup hangi kelimenin talep getirdiğini gördükten sonra bütçeyi o tarafa kaydırıyor, inen sayfayı düzeltiyoruz.',
            '{{region}} Google Ads hesabı bize mi ait olacak?' => 'Evet. Reklam hesabı sizin adınıza açılır, faturalandırma sizin bilgilerinizle yapılır, yönetici erişimimiz ise hizmet süresince tanımlı kalır. Hizmet bittiğinde hesap, kampanya geçmişi ve birikmiş dönüşüm verisi sizde kalır; kimse sıfırdan kurmak zorunda kalmaz. {{region}} kampanyalarının performans geçmişi de aynı hesapta durur.',
            'Rakiplerim marka adıma reklam veriyor, {{region}} içinde bunu engelleyebilir miyiz?' => 'Rakipler marka adınızı anahtar kelime olarak hedefleyebilir; Google bunu genel olarak yasaklamaz. Ancak tescilli markanız reklam metninde izinsiz kullanılıyorsa Google’a marka şikâyeti yapılabilir. Pratikte en etkili karşılık kendi marka adınıza düşük maliyetle reklam vermektir: marka aramalarında ilk sırayı korur ve {{region}} içindeki rakip reklamının tıklama payını belirgin biçimde düşürür.',
            '{{region}} Google Ads raporlarını nasıl takip edeceğim?' => 'Reklam hesabınıza her zaman erişebilirsiniz; ayrıca harcama, tıklama, dönüşüm sayısı ve müşteri edinme maliyetini gösteren düzenli bir rapor gönderiyoruz. Formdan ve telefondan gelen talepler dönüşüm olarak ölçüldüğü için “reklam para getirdi mi” sorusunun cevabı tahmine değil veriye dayanır. {{region}} için hangi kelimenin kaç talep getirdiğini de raporda kalem kalem görürsünüz.',
        ],
    ];

    public function run(): void
    {
        $sort = (int) Faq::max('sort_order');

        foreach (self::FAQS as $service => $rows) {
            $created = 0;

            foreach ($rows as $question => $answer) {
                $faq = Faq::firstOrCreate(
                    ['question' => $question],
                    ['answer' => $answer, 'is_active' => true, 'sort_order' => ++$sort],
                );

                if ($faq->wasRecentlyCreated) {
                    $created++;
                }
            }

            $this->command?->info("{$service}: ".count($rows)." soru hazır ({$created} yeni).");
        }

        $this->command?->info('Sorular havuza yazıldı; hizmetlere bağlanması panelden yapılır.');
    }
}
